### ISSUE TITLE
[gazebo_ros_control] Supports multi-turn joints when using PID mode

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/gazebo_ros_pkgs#2]
**Summery**
- For REVOLUTE type joints, joints with a range of motion greater than one revolution do not operate properly. (Only when PID is enabled)
- The following programs are causing the problem
https://github.com/sbgisen/gazebo_ros_pkgs/blob/b0e3d71938e4cd4c80a2ec3ff7187aac49a9f62a/gazebo_ros_control/src/default_robot_hw_sim.cpp#L328-L346
- REVOLUTE joint has exception handling to keep the target angle within the range of motion, but this includes a function that does not work correctly if the range of motion is more than one revolution.
- The CONTINUOUS joint can handle more than one rotation, but the algorithm is designed to reverse the rotation in an attempt to take a shortcut when the target angle deviates more than half a revolution from the current angle.
- If the "default" in the case statement is used as is, the operation will correspond to a multi-turn joint.

**Comment by jsupratman13** [comment]
The function in question `angles::shortest_angular_distance_with_limits` is described in the link below
http://docs.ros.org/en/melodic/api/angles/html/namespaceangles.html#a4436fe67ae0c9df020f6779101bbefab 

In addition, the question about the position controller only working properly within the [-pi, pi] range are addressed in the issues below
* https://github.com/ros-simulation/gazebo_ros_pkgs/issues/812
* https://github.com/ros-controls/ros_controllers/issues/365#issuecomment-537897846

**Comment by jsupratman13** [comment]
An extension of `angles::shortest_angular_distance_with_limits` with a larger range was made in the PR below
https://github.com/ros/angles/pull/16

**Comment by nyxrobotics** [comment]
Thanks for the info.
If the target angle doesn't jump more than half a circle at once, it seems to me that using the same function as ros_controllers would be easier to handle.

**Comment by nyxrobotics** [comment]
I'll take  `angles::shortest_angular_distance_with_limits`  for now.
